default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: 192.168.15.67
  database: ios_container_inspection
  port: 5432
  username: postgres
  password: hbn110900

test:
  <<: *default
  host: 192.168.15.67
  database: ios_container_inspection
  port: 5432
  username: postgres
  password: hbn110900

production:
  <<: *default
  database: ios_container_inspection
  username: postgres
  password: hbn110900
